services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123

  shirt:
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
